service:
  name: "otp-auth-service"
  env: "development"
  gracefulShutdownSecond: 5
  http:
    port: "8081"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  databaseName: "otpauth"
  sslMode: "disable"
  timeZone: "UTC"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  expirationHours: 24

otp:
  expiration: 120 # seconds
  length: 6
  rateLimit:
    count: 3
    time: 10 # minutes
